from typing import Any, TypedDict

class ExecutionBlocker:
	def __init__(self, message: str | None) -> None: ...

class GraphBuilder:
	def __init__(self, prefix: str | None = None) -> None: ...

	@classmethod
	def alloc_prefix(
		cls,
		root: str | None = None,
		call_index: int | None = None,
		graph_index: int | None = None,
	) -> str: ...

	@classmethod
	def set_default_prefix(cls, prefix_root: str, call_index: int, graph_index: int = 0) -> None: ...

	def finalize(self) -> dict[str, _Node_serialized]: ...

	def lookup_node(self, id: str) -> Node | None: ...

	def node(self, class_type: str, id: str | None = None, **kwargs: Any) -> Node: ...

	def remove_node(self, id: str) -> None: ...

	def replace_node_output(self, node_id: str, index: int, new_value: Any) -> None: ...

class Node:
	def __init__(self, id: str, class_type: str, inputs: dict[str, Any]) -> None: ...

	def get_input(self, key: str) -> Any: ...

	def out(self, index: int) -> tuple[str, int]: ...

	def serialize(self) -> _Node_serialized: ...

	def set_input(self, key: str, value: Any) -> None: ...

	def set_override_display_id(self, override_display_id: str) -> None: ...

class _Node_serialized(TypedDict):
	class_type: str
	inputs: dict[str, Any]
