from .float import OneFloat as OneFloat
from .float_add import OneFloatAdd as OneFloatAdd
from .float_ceil import OneFloatCeil as OneFloatCeil
from .float_divide import OneFloatDivide as OneFloatDivide
from .float_evaluate import OneFloatEvaluate as OneFloatEvaluate
from .float_exponentiate import OneFloatExponentiate as OneFloatExponentiate
from .float_floor import OneFloatFloor as OneFloatFloor
from .float_max import OneFloatMax as OneFloatMax
from .float_min import OneFloatMin as OneFloatMin
from .float_multiply import OneFloatMultiply as OneFloatMultiply
from .float_round import OneFloatRound as OneFloatRound
from .float_subtract import OneFloatSubtract as OneFloatSubtract
