[build-system]
requires = ["uv_build >=0.12.10, <0.13.0"]
build-backend = "uv_build"

[project]
name = "one"
version = "0.0.1"
dependencies = [
	"jsrun >=0.1.0",
	"torch >=2.12.0"
]
requires-python = ">=3.10, <3.15"
authors = [{name = "Ian Sun", email = "me@sunyun.name"}]
license = "MIT"

[project.urls]
Repository = "https://github.com/IanSun/ComfyUI-One.git"

[tool.uv.build-backend]
module-name = "one"
module-root = "packages"
source-exclude = [
	"ui/node_modules",
	"ui/src",
	"ui/package.json",
	"ui/project.json",
	"ui/tsconfig.json",
	"ui/tsconfig.node.json",
	"ui/tsconfig.ui.json",
	"ui/vite.config.ts"
]
