name: 发布

on:
  push:
    branches:
      - main
    paths:
      - packages/one/locales/**/*.json
      - packages/one/**/*.py
      - packages/one/ui/src/**/*.ts
      - packages/one/ui/tsconfig.ui.json
      - packages/one/ui/vite.config.ts
      - pnpm-lock.yaml
      - pyproject.toml

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: 检查项目版本与版本发布状态
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: 检出项目源码
        uses: actions/checkout@v7
      - name: 设置 uv 环境
        uses: astral-sh/setup-uv@v10.1.0
      - id: get-version
        name: 获取项目版本号
        run: |
          VERSION="$(uv version --short)"
          if gh release view "v${VERSION}" >/dev/null 2>&1
          then
            echo "::notice::已存在 Release v${VERSION}"
          else
            echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
          fi

  build:
    name: 构建产物
    needs: check
    if: needs.check.outputs.version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.check.outputs.version }}
    steps:
      - name: 检出项目源码
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: 设置 pnpm 环境
        uses: pnpm/setup@v2
      - name: 构建产物
        run: pnpm build
      - name: 设置 uv 环境
        uses: astral-sh/setup-uv@v10.1.0
      - name: 构建产物
        run: uv build
      - name: 上传产物
        uses: actions/upload-artifact@v7
        with:
          path: dist/*.whl
          if-no-files-found: error
          retention-days: 1

  publish:
    name: 发布
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 检出项目源码
        uses: actions/checkout@v7
      - name: 下载产物
        uses: actions/download-artifact@v8
        with:
          path: dist
      - name: 发布
        run: |
          gh release create "v${{ needs.build.outputs.version }}" "dist/*"
        env:
          GH_TOKEN: ${{ github.token }}
